version: '3.1'

services:
  mysql:
    image: 'mysql:latest'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ilunch
      MYSQL_DATABASE: ilunch
    volumes:
      - ./mysql:/var/lib/mysql

  admin:
    image: adminer
    ports:
      - '8081:8080'
    depends_on:
      - mysql
